### ISSUE TITLE
suporte pra caracteres '?' e '=' no ZQRcode

### ISSUE THREAD

**Issue by nicociri** [siga0984/zLIB#1]
Julio, pra codificar URL de tipo GET (por exemplo: www.web.com/param?P1=valor) tentei agregar os caracteres ? e = na funcao getalpha... mas nao consigo un qr que funcione... ele gera un qr, mas nao e reconhecido por nenhum celular que eu tem pra testear.

	aadd(_Alpha,{'?', 45 })
	aadd(_Alpha,{'=', 46 })

o preciso fazer algo mais?

**Comment by siga0984** [comment]
Opa, beleza ? Então ... o alfabeto alfanumérico ( tipo 2 ) é restrito, não
podem entrar novos caracteres ...
O correto a fazer neste caso é passar o modo 3 no método SetData(cQRData,
nMode)
Experimente e me conte se deu certo -- deveria funcionar ..rs..
E remova os "add" que você colocou no _Alpha , ok?

Abraços

*Júlio Wittwer*
siga0984@gmail.com
https://siga0984.wordpress.com/
https://www.facebook.com/siga0984

**Comment by nicociri** [comment]
Obrigado Julio. Entao volta a versao original.  Apenas para confirmar que o problema não é meu código, eu tome seu codigo no blog (https://siga0984.wordpress.com/2019/05/26/qr-code-em-advpl-parte-03/) e tampoco consigo gerar um qr valido, incluso trocando Local nMode := 3

Acho que e um problema com os dados. Um string do tipo "hola mundo" funciona bem, mas meu string e uma URL com parametros encodeados na base 64:

https://www.afip.gob.ar/fe/qr/?p=W1sidmVyIiwgMV0sIFsiZmVjaGEiLCAiMjAyMC0xMC0yOCJdLCBbImN1aXQiLCAzMDUzNjY2ODI0OF0sIFsicHRvVnRhIiwgMjRdLCBbInRpcG9DbXAiLCAwXSwgWyJucm9DbXAiLCAyMTQ3XSwgWyJpbXBvcnRlIiwgODEyOF0sIFsibW9uZWRhIiwgIlBFUyJdLCBbImN0eiIsIDFdLCBbInRpcG9Eb2NSZWMiLCA4MF0sIFsibnJvRG9jUmVjIiwgMzA3MTQ4NjE1OTZdLCBbInRpcG9Db2RBdXQiLCAiRSJdLCBbImNvZEF1dCIsIDcwNDQ4OTcxNjU0MDg2XV0=

esa url gera um qr, mas ese qr nao e reconhecido. E um limite da libreria ou eu deveria fazer as coissas de outro jeito?

(desculpas por meu portugues... e bem ruim).... Feliz Ano novo!

**Comment by siga0984** [comment]
Olá,

Então, pode ser uma limitação da LIB .. Eu nao testei ela com QR Codes
muito grandes -- como é o caso desse que você quer gerar...  Existem 40
"versões" de QR Code, quanto maior a versão, mais dados cabem dentro, mas
quanto maior a versão, maiores são as quebras internas dos layouts de
dados. Para essa URL caber dentro de um QR code codificado em nMode = 3 (
utf8 / bytes ), com a correção de erro "L" ( Low error correction -default
), ele deve ser gerado com a versão 13 ... eu acho que testei a lib até
versões 8 ou 9 do QR Code ...

A matriz de testes é muito grande, essa lib em AdvPL serve para criar QR
Codes "menores" ... Verifique na TDN se o produto padrão já não tem uma
alternativa para gerar os QR Codes :D


*Júlio Wittwer*
siga0984@gmail.com
https://siga0984.wordpress.com/
https://www.facebook.com/siga0984

**Comment by siga0984** [comment]
Dê uma olhada na TDN, se você está usando o ERP Padrão, tem uma classe para
gerar QR Code :D

https://tdn.totvs.com/display/public/PROT/FwQrCode

E, feliz ano novo para você e família !!!

😎

*Júlio Wittwer*
siga0984@gmail.com
https://siga0984.wordpress.com/
https://www.facebook.com/siga0984

**Comment by nicociri** [comment]
ola Julio! Eu uso esa classe pra os protheus 11 e 12 e funciona bem... mas aqui na argentina ainda temos varias empresas con P10.. e P10 nao atualizado... e quase arqueologia do sistemas... :D

bom... sera um argumento pra finalmente conseguir que eles migren de versao. Muito obrigado pela ajuda Julio!!

**Comment by siga0984** [comment]
De nada , magina ! :D Boa sorte aí !! Abraços

*Júlio Wittwer*
siga0984@gmail.com
https://siga0984.wordpress.com/
https://www.facebook.com/siga0984
